spring:
  profiles:
    active: dev
  application:
    name: snake-framework-test-api

server:
  port: 8971

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}