eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ## 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/