spring:
  profiles:
    active: dev
  application:
    name: snake-framework-test-gateway

server:
  port: 8972

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}